# Generated by Django 4.2.10 on 2024-02-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="read",
            field=models.BooleanField(default=True),
        ),
    ]
